/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
FirstVstAudioProcessorEditor::FirstVstAudioProcessorEditor (FirstVstAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter),
	  myFilter (ownerFilter),
	  gridComponent (nullptr)
{
	bgColor = Colours::white;
	startTimer(100);

	addAndMakeVisible(gridComponent = new GridComponent(myFilter));
	    
	setSize (400, 300);
}

FirstVstAudioProcessorEditor::~FirstVstAudioProcessorEditor()
{
}

//==============================================================================
void FirstVstAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (bgColor);
    g.setColour (Colours::black);
    g.setFont (15.0f);
	g.drawFittedText ("PPQ: " + String(myFilter->lastPosInfo.ppqPosition),
                      0, 0, getWidth(), getHeight(),
                      Justification::centred, 1);
}

void FirstVstAudioProcessorEditor::resized() {
	gridComponent->setBounds(10, 10, getWidth() - 20, getHeight() - 20);
}

void FirstVstAudioProcessorEditor::timerCallback() {
	repaint();
}