/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_3D990D60__
#define __PLUGINEDITOR_H_3D990D60__

#include "../JuceLibraryCode/JuceHeader.h"
#include "../JuceLibraryCode/JucePluginCharacteristics.h"
#include "PluginProcessor.h"
#include "GridComponent.h"

//==============================================================================
/**
*/
class FirstVstAudioProcessorEditor  : public AudioProcessorEditor, public Timer
{
public:
    FirstVstAudioProcessorEditor (FirstVstAudioProcessor* ownerFilter);
    ~FirstVstAudioProcessorEditor();

	//Timer methods
	virtual void timerCallback();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
	void resized();

private:
	Colour bgColor;
	FirstVstAudioProcessor* myFilter;
	ScopedPointer<GridComponent> gridComponent;
};


#endif  // __PLUGINEDITOR_H_3D990D60__
